#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEliminatoria_EdgarDuarte_1193520.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="partidoDB")]
	public partial class PartidoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEquipo(Equipo instance);
    partial void UpdateEquipo(Equipo instance);
    partial void DeleteEquipo(Equipo instance);
    partial void InsertPartido(Partido instance);
    partial void UpdatePartido(Partido instance);
    partial void DeletePartido(Partido instance);
    #endregion
		
		public PartidoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["partidoDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartidoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Equipo> Equipo
		{
			get
			{
				return this.GetTable<Equipo>();
			}
		}
		
		public System.Data.Linq.Table<Partido> Partido
		{
			get
			{
				return this.GetTable<Partido>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPRegistroPartido")]
		public int SPRegistroPartido([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codequipo1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codequipo2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gol1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gol2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codequipo1, codequipo2, fecha, gol1, gol2);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarPosiciones")]
		public ISingleResult<SP_ListarPosicionesResult> SP_ListarPosiciones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarPosicionesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.equipo")]
	public partial class Equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _puntos;
		
		private EntitySet<Partido> _Partido;
		
		private EntitySet<Partido> _Partido1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnpuntosChanging(System.Nullable<int> value);
    partial void OnpuntosChanged();
    #endregion
		
		public Equipo()
		{
			this._Partido = new EntitySet<Partido>(new Action<Partido>(this.attach_Partido), new Action<Partido>(this.detach_Partido));
			this._Partido1 = new EntitySet<Partido>(new Action<Partido>(this.attach_Partido1), new Action<Partido>(this.detach_Partido1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Int")]
		public System.Nullable<int> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Partido", Storage="_Partido", ThisKey="id", OtherKey="idequipo1")]
		public EntitySet<Partido> Partido
		{
			get
			{
				return this._Partido;
			}
			set
			{
				this._Partido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Partido1", Storage="_Partido1", ThisKey="id", OtherKey="idequipo2")]
		public EntitySet<Partido> Partido1
		{
			get
			{
				return this._Partido1;
			}
			set
			{
				this._Partido1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partido(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = this;
		}
		
		private void detach_Partido(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = null;
		}
		
		private void attach_Partido1(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = this;
		}
		
		private void detach_Partido1(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Partido")]
	public partial class Partido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _idequipo1;
		
		private System.Nullable<int> _idequipo2;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _goles1;
		
		private System.Nullable<int> _goles2;
		
		private EntityRef<Equipo> _Equipo;
		
		private EntityRef<Equipo> _Equipo1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onidequipo1Changing(System.Nullable<int> value);
    partial void Onidequipo1Changed();
    partial void Onidequipo2Changing(System.Nullable<int> value);
    partial void Onidequipo2Changed();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void Ongoles1Changing(System.Nullable<int> value);
    partial void Ongoles1Changed();
    partial void Ongoles2Changing(System.Nullable<int> value);
    partial void Ongoles2Changed();
    #endregion
		
		public Partido()
		{
			this._Equipo = default(EntityRef<Equipo>);
			this._Equipo1 = default(EntityRef<Equipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idequipo1", DbType="Int")]
		public System.Nullable<int> idequipo1
		{
			get
			{
				return this._idequipo1;
			}
			set
			{
				if ((this._idequipo1 != value))
				{
					if (this._Equipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onidequipo1Changing(value);
					this.SendPropertyChanging();
					this._idequipo1 = value;
					this.SendPropertyChanged("idequipo1");
					this.Onidequipo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idequipo2", DbType="Int")]
		public System.Nullable<int> idequipo2
		{
			get
			{
				return this._idequipo2;
			}
			set
			{
				if ((this._idequipo2 != value))
				{
					if (this._Equipo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onidequipo2Changing(value);
					this.SendPropertyChanging();
					this._idequipo2 = value;
					this.SendPropertyChanged("idequipo2");
					this.Onidequipo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goles1", DbType="Int")]
		public System.Nullable<int> goles1
		{
			get
			{
				return this._goles1;
			}
			set
			{
				if ((this._goles1 != value))
				{
					this.Ongoles1Changing(value);
					this.SendPropertyChanging();
					this._goles1 = value;
					this.SendPropertyChanged("goles1");
					this.Ongoles1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_goles2", DbType="Int")]
		public System.Nullable<int> goles2
		{
			get
			{
				return this._goles2;
			}
			set
			{
				if ((this._goles2 != value))
				{
					this.Ongoles2Changing(value);
					this.SendPropertyChanging();
					this._goles2 = value;
					this.SendPropertyChanged("goles2");
					this.Ongoles2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Partido", Storage="_Equipo", ThisKey="idequipo1", OtherKey="id", IsForeignKey=true)]
		public Equipo Equipo
		{
			get
			{
				return this._Equipo.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo.Entity;
				if (((previousValue != value) 
							|| (this._Equipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo.Entity = null;
						previousValue.Partido.Remove(this);
					}
					this._Equipo.Entity = value;
					if ((value != null))
					{
						value.Partido.Add(this);
						this._idequipo1 = value.id;
					}
					else
					{
						this._idequipo1 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Equipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Partido1", Storage="_Equipo1", ThisKey="idequipo2", OtherKey="id", IsForeignKey=true)]
		public Equipo Equipo1
		{
			get
			{
				return this._Equipo1.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo1.Entity;
				if (((previousValue != value) 
							|| (this._Equipo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo1.Entity = null;
						previousValue.Partido1.Remove(this);
					}
					this._Equipo1.Entity = value;
					if ((value != null))
					{
						value.Partido1.Add(this);
						this._idequipo2 = value.id;
					}
					else
					{
						this._idequipo2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("Equipo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_ListarPosicionesResult
	{
		
		private string _nombre;
		
		private System.Nullable<int> _Puntos;
		
		private System.Nullable<int> _GolesAF;
		
		private System.Nullable<int> _GolesEC;
		
		public SP_ListarPosicionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(40)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntos", DbType="Int")]
		public System.Nullable<int> Puntos
		{
			get
			{
				return this._Puntos;
			}
			set
			{
				if ((this._Puntos != value))
				{
					this._Puntos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GolesAF", DbType="Int")]
		public System.Nullable<int> GolesAF
		{
			get
			{
				return this._GolesAF;
			}
			set
			{
				if ((this._GolesAF != value))
				{
					this._GolesAF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GolesEC", DbType="Int")]
		public System.Nullable<int> GolesEC
		{
			get
			{
				return this._GolesEC;
			}
			set
			{
				if ((this._GolesEC != value))
				{
					this._GolesEC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
